# Generated by Django 5.1.2 on 2024-10-28 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_libraryframework_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalskill',
            name='slug',
            field=models.SlugField(default='hi'),
        ),
        migrations.AddField(
            model_name='language',
            name='slug',
            field=models.SlugField(default='hi'),
        ),
        migrations.AddField(
            model_name='libraryframework',
            name='slug',
            field=models.SlugField(default='hi'),
        ),
    ]
