# Generated by Django 5.1.2 on 2024-10-28 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_project_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalskill',
            name='description',
        ),
        migrations.RemoveField(
            model_name='language',
            name='description',
        ),
        migrations.RemoveField(
            model_name='libraryframework',
            name='description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.AlterField(
            model_name='generalskill',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='language',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='libraryframework',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(),
        ),
    ]
