# Generated by Django 5.1.2 on 2024-10-31 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_remove_generalskill_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generalskill",
            name="slug",
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name="language",
            name="slug",
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name="libraryframework",
            name="slug",
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="slug",
            field=models.SlugField(blank=True),
        ),
    ]
