# Generated by Django 5.1.2 on 2024-11-04 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_generalskill_slug_alter_language_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalskill',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='language',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='libraryframework',
            name='experience',
        ),
        migrations.AddField(
            model_name='generalskill',
            name='began_learning',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='began_learning',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='libraryframework',
            name='began_learning',
            field=models.DateField(blank=True, null=True),
        ),
    ]
