# Generated by Django 5.1.3 on 2024-11-13 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_generalskill_began_learning_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalskill',
            name='is_learning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='language',
            name='is_learning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='libraryframework',
            name='is_learning',
            field=models.BooleanField(default=False),
        ),
    ]
