# Generated by Django 5.2.4 on 2025-07-14 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(default='Description here')),
                ('maintenance_mode', models.BooleanField(default=False, help_text='Will prevent the site from being accessed by non-staff. The maintenance message will be displayed.')),
                ('maintenance_message', models.TextField(default="We're curreuntly under maintenance! Check back soon!")),
            ],
            options={
                'verbose_name': 'configuration',
            },
        ),
        migrations.CreateModel(
            name='WebsiteContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('is_primary', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('phone', 'Phone'), ('email', 'Email')], help_text='The type of contact.', max_length=32)),
                ('contact', models.CharField(help_text='The actual contact information (phone number/email address).', max_length=64)),
                ('svg', models.TextField(blank=True, help_text='The HTML svg icon of the social.', null=True)),
            ],
            options={
                'verbose_name': 'contact',
                'verbose_name_plural': 'contacts',
            },
        ),
        migrations.CreateModel(
            name='WebsiteSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('svg', models.TextField(help_text='The HTML svg icon of the social.')),
                ('link', models.URLField(help_text='The link to the actual social page.')),
            ],
            options={
                'verbose_name': 'social',
                'verbose_name_plural': 'socials',
            },
        ),
    ]
