# Generated by Django 5.2.4 on 2025-07-14 03:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('slug', models.SlugField(editable=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('slug', models.SlugField(editable=False)),
                ('began_learning', models.DateField(default=django.utils.timezone.localdate)),
                ('tags', models.ManyToManyField(blank=True, related_name='skills', to='main.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('slug', models.SlugField(editable=False)),
                ('began_learning', models.DateField(default=django.utils.timezone.localdate)),
                ('tags', models.ManyToManyField(blank=True, related_name='languages', to='main.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('slug', models.SlugField(editable=False)),
                ('began_learning', models.DateField(default=django.utils.timezone.localdate)),
                ('tags', models.ManyToManyField(blank=True, related_name='technologies', to='main.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('slug', models.SlugField(editable=False)),
                ('began_learning', models.DateField(default=django.utils.timezone.localdate)),
                ('tags', models.ManyToManyField(blank=True, related_name='tools', to='main.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
