# Generated by Django 5.2.4 on 2025-07-14 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_tag_skill_language_technology_tool'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='svg',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='svg',
            field=models.TextField(default='def'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='technology',
            name='svg',
            field=models.TextField(default='def'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tool',
            name='svg',
            field=models.TextField(default='def'),
            preserve_default=False,
        ),
    ]
