# Generated by Django 5.2.4 on 2025-07-15 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_language_svg_skill_svg_technology_svg_tool_svg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='svg',
            new_name='icon',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='svg',
            new_name='icon',
        ),
        migrations.RenameField(
            model_name='technology',
            old_name='svg',
            new_name='icon',
        ),
        migrations.RenameField(
            model_name='tool',
            old_name='svg',
            new_name='icon',
        ),
    ]
